
enum TokenType {
    Integer,
    Float
//     FLOAT,
//     STRING,
//     BOOL,
//     IF,
//     ELSE,
//     WHILE,
//     SEMICOLON,
//     TRU,
//     FALS,
//     COLON,
//     NAME,
//     LPAREN,
//     RPAREN,
//     LBRACE,
//     RBRACE,
//     EQUAL,
//     PLUS,
//     MINUS,
//     MULTIPLY,
//     DIVIDE,
//     RETURN,
//     FOR,
//     PRINT,
//     QUOTE,
//     DOUBLEQUOTE,
//     VALUE,
//     IMPORT,
//     COMMENT,
//     EMPTYLINE,
//     UKNOWN,
//     SPACE,
//     EMPTY,
//     NEWLINES,
//     GREATER,
//     LESS,
//     IN,
//     RBRACKET,
//     LBRACKET,
//     UKNOWN_INT,
//     UKNOWN_STRING,
//     UKNOWN_FLOAT,
//     UKNOWN_VARNAME,
//     RANGE_SKIP,
//     VALUE_BOOL,
//     RANGE,
//     PATH,
//     COMMA,
//     SPACES,
//     STRING_INT,
//     VALUE_STRING,
//     NEWLINE
// }
}
